### ISSUE TITLE
Upgrade duplicate finding logic with edit distance

### ISSUE THREAD

**Issue by vinayak-mehta** [vinayak-mehta/conrad#11]
We could have a threshold (`0.5` or `0.7`) above which a conference could be flagged as a duplicate during import.

**Comment by Sangarshanan** [comment]
We could use Levenshtein or difflib.SequenceMatcher. There is a stackoverflow answer comparing the [Performance and Tradeoffs](https://stackoverflow.com/questions/6690739/high-performance-fuzzy-string-comparison-in-python-use-levenshtein-or-difflib) of both

**Comment by nishant-sethi** [comment]
@vinayak-mehta is this issue still open?

**Comment by vinayak-mehta** [comment]
@Sangarshanan was working on this. If he is not working on it, then you can take this up :)

**Comment by nishant-sethi** [comment]
@Sangarshanan can you please confirm if you are working or not.

**Comment by Sangarshanan** [comment]
I am not working on this currently. You could take this up if you want @nishant-sethi

**Comment by nishant-sethi** [comment]
@vinayak-mehta I'll pick it up. @Sangarshanan can you please tell me in which file changes are required.
@vinayak-mehta Can you please me the overview about what change is required.

**Comment by nishant-sethi** [comment]
@Sangarshanan Thanks for the suggestion. I'll try to work on this today and raise PR based on which you can provide feedback.

**Comment by JosemyDuarte** [comment]
Hi pps! Do you keep working on this @nishant-sethi? I can take it if it's free.

**Comment by nishant-sethi** [comment]
@JosemyDuarte you can take this up

**Comment by JosemyDuarte** [comment]
Hi @vinayak-mehta! I just opened a PR for this. Whenever you can, please let me know your feedback.
