### ISSUE TITLE
Add scraper for PyData

### ISSUE THREAD

**Issue by vinayak-mehta** [vinayak-mehta/conrad#15]

**Comment by CristhianMotoche** [comment]
Hello @vinayak-mehta Can I pick this one?
I suppose we want to get the list of events from [here](https://pydata.org/event-schedule/), right?

**Comment by vinayak-mehta** [comment]
Yes! Please go ahead :)

**Comment by vinayak-mehta** [comment]
Fixed by b9bce61.
