### ISSUE TITLE
Add motivational messages to conrad remind

### ISSUE THREAD

**Issue by vinayak-mehta** [vinayak-mehta/conrad#18]
Like a positive `fortune` with quotes about submitting a proposal and taking that first step forward.

**Comment by vinayak-mehta** [comment]
https://en.wikipedia.org/wiki/Fortune_(Unix)

**Comment by allenmac347** [comment]
Hi, I'm a beginner looking to make my first open source contribution. May I try to fix this issue?

**Comment by Ghost519** [comment]
@allenmac347  I am in the same boat, did you fix it?

**Comment by TheKnightWhoSaidNI** [comment]
#130 I added a function that prints a fortune after reminders

**Comment by adya-13** [comment]
Hi, I am new to open source and looking for my first contribution. If this issue is still open, may I try and fix this?

**Comment by GK230** [comment]
Hi, I tried to install conrad using pip, but I get this error: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5w/0v1ns3353w59xjlhq5llhrb40000gp/T/pip-build-9GmZSA/conference-radar/setup.py", line 10, in <module>
        exec(f.read(), about)
      File "<string>", line 11
        version_parts.append(f"-{prerelease}")
                                            ^
    SyntaxError: invalid syntax

**Comment by vinayak-mehta** [comment]
Closing this issue for now, not sure if it's really useful. Please let me know if you'd want something like this.

@GK230 You'll need Python>=3.6

**Comment by lglista** [comment]
First time contributor, I saw this on TODO and thought I would pick it up
