### ISSUE TITLE
Informative validations on conrad import 

### ISSUE THREAD

**Issue by Sangarshanan** [vinayak-mehta/conrad#21]

**Comment by vinayak-mehta** [comment]
@Sangarshanan Can you add more details?

**Comment by Sangarshanan** [comment]
Instead of returning a list https://github.com/vinayak-mehta/conrad/blob/01fbc34526f72b6109c077a2032859ac9de5ed92/conrad/utils.py#L51  could return more information and why the validation failed for each element of the list
