### ISSUE TITLE
Add help text to all commands

### ISSUE THREAD

**Issue by vinayak-mehta** [vinayak-mehta/conrad#23]
https://click.palletsprojects.com/en/7.x/documentation/#help-texts

**Comment by JosemyDuarte** [comment]
Hello!

I can jump into this one. Are there any specific messages we would like to show? Or should I write what seems most appropriate?

**Comment by vinayak-mehta** [comment]
Hi @JosemyDuarte! You can start out with this and edit this based on your understanding of these commands from the README :)

```
import: Import new events into conrad
refresh: Refresh event database
remind: Set and display reminders
show: Query event database
```

**Comment by JosemyDuarte** [comment]
PR done. I have some doubts about what to put for `remind -i`. What would you suggest?
