### ISSUE TITLE
Weird bug in conrad import 

### ISSUE THREAD

**Issue by Sangarshanan** [vinayak-mehta/conrad#25]
Tried conrad import with [conrad.zip](https://github.com/vinayak-mehta/conrad/files/3778398/conrad.zip) (extract for json)

The first time It gave me a validation error even though there are no duplicates event names

Another time it updated events.json but did not echo the string saying that these were updated...it ran successfully silently.  https://github.com/vinayak-mehta/conrad/blob/01fbc34526f72b6109c077a2032859ac9de5ed92/conrad/cli.py#L276

The third time it runs successfully

![Screenshot from 2019-10-28 16-51-12](https://user-images.githubusercontent.com/21971847/67674675-29ee9d80-f9a3-11e9-84ce-1cb4d39142d6.png)

**Comment by vinayak-mehta** [comment]
Thanks for the report! I'll check it out.
