### ISSUE TITLE
Refresh database when it is > 2 hours

### ISSUE THREAD

**Issue by vinayak-mehta** [vinayak-mehta/conrad#33]
When show is run.

**Comment by anusha5695** [comment]
@vinayak-mehta : Can i pick this?

**Comment by anusha5695** [comment]
I got a working code

**Comment by anusha5695** [comment]
Sorry i committed the changes for this issue in another. PR : https://github.com/vinayak-mehta/conrad/pull/39

**Comment by anusha5695** [comment]
Hi @vinayak-mehta : PR link https://github.com/vinayak-mehta/conrad/pull/40
