### ISSUE TITLE
Check for new conrad version

### ISSUE THREAD

**Issue by vinayak-mehta** [vinayak-mehta/conrad#36]
Compare user's `conrad.__version__` with the latest release on PyPI and suggest them to upgrade conrad periodically.

**Comment by abhi-baireddy** [comment]
@vinayak-mehta I worked on this. I added a new function in the __main__.py file that gets the current version of conference-radar using the PyPI API, checks if it is the latest and prompts the user to upgrade if so. I am not quite sure if I made the changes in the right place. Please help me if I got it wrong or if there's anything I can improve. This is my first ever contribution. 

After I made the PR, deepsource showed some errors. I will take care of them if what I did is correct in the first place. I'm still learning!

Thanks!
