### ISSUE TITLE
Standardize scraped location to city, state, country and latlongs 

### ISSUE THREAD

**Issue by Sangarshanan** [vinayak-mehta/conrad#37]
Could use [Nominatim](https://wiki.openstreetmap.org/wiki/Nominatim)

**Comment by vinayak-mehta** [comment]
This could be a conrad util that everyone can use in their scapers.

**Comment by vinayak-mehta** [comment]
Or a code snippet that anyone can copy|paste and use directly

**Comment by vinayak-mehta** [comment]
We could then give users nearby conferences using their location.

**Comment by vinayak-mehta** [comment]
We can use https://geopy.readthedocs.io with MapBox!

**Comment by vinayak-mehta** [comment]
Alas, data returned from the MapBox API can't be stored :(

**Comment by Sangarshanan** [comment]
Could check out [Here API](https://developer.here.com/pricing) or [TomTom](https://developer.tomtom.com/store/maps-api)  Both of em have a free tier and  are pretty good.

**Comment by kunaljubce** [comment]
Hi,

I am starting working on this. Should I develop this as a custom module placed in the conrad/conrad/ folder, which can then be imported into the crawlers?
