### ISSUE TITLE
Remove reminder when conference starts

### ISSUE THREAD

**Issue by vinayak-mehta** [vinayak-mehta/conrad#58]

**Comment by rhaerma** [comment]
hi. mind if i work on this?

**Comment by vinayak-mehta** [comment]
Please go ahead :)

**Comment by rhaerma** [comment]
kindly review my PR #59

**Comment by rhaerma** [comment]
@vinayak-mehta kindly review my PR #59

**Comment by rhaerma** [comment]
hi what happened to my PR #59 ? can you elaborate clearly? thanks

**Comment by vinayak-mehta** [comment]
Hey it'll be handled in an auto-update function outside of `_remind`, which will also include some other steps.
