### ISSUE TITLE
Conrad remind should check CONRAD_HOME exist before running

### ISSUE THREAD

**Issue by JosemyDuarte** [vinayak-mehta/conrad#66]
Right now if you have a clean `conrad` env and you run `conrad remind` it will fail bc the DB doesn't exist yet. You need to execute `refresh` first. 

Before executing `remind` command might be a good idea to check if the db exists and suggest the user to run `refresh` first.

**Comment by vinayak-mehta** [comment]
@JosemyDuarte Thanks for the report!

**Comment by JosemyDuarte** [comment]
No problem. It's ok if I work on this?

**Comment by JosemyDuarte** [comment]
You have my proposal in this [PR](https://github.com/vinayak-mehta/conrad/pull/67). I have it as [WIP] just in case you think that it is not a good approach. But actually it is completely functional. Let me know what you think.
