### ISSUE TITLE
conrad errors trying to open database file before first refresh

### ISSUE THREAD

**Issue by Xevion** [vinayak-mehta/conrad#8]
Hi, I was looking through Hacktoberfest issues when I found your module and downloaded it.
When I first ran `pip install conference-radar`, the pip installer froze for a good 2-3 minutes before I `CTRL+C` quit out of it. Running it again seemed to have zero effect, so I continued onward.

Running `conrad show` returned a DB error, perhaps a DB is not properly created before running `conrad refresh`? I don't personally know since I have yet to understand the project.

[**Full Terminal Output**](https://gist.githubusercontent.com/Xevion/89ac6bbc9bf1d8b2976d57a828520b63/raw/6212f7c9701f7ffdb78ec128db29a0599d4a9d7b/gistfile1.txt)

**Comment by Naveenkhasyap** [comment]
I am fixing this raising PR for the same.

**Comment by vinayak-mehta** [comment]
@Xevion Thanks for using the project! Can you also give details about your Python version and operating system?

**Comment by vinayak-mehta** [comment]
@Xevion Just went through the terminal output, this was supposed to be intended behavior (as shown in the README) but I see how just one command `conrad show` should do the trick! Certainly more easier than refreshing the database the first time.

**Comment by Xevion** [comment]
```python
Microsoft Windows [Version 10.0.17134.471]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Xevion>python --version
Python 3.7.4
```
Cool. And just to be clear, you intend to fix it so that the error doesn't appear in the form of a 80 line output? Haha.

**Comment by vinayak-mehta** [comment]
> Cool. And just to be clear, you intend to fix it so that the error doesn't appear in the form of a 80 line output? Haha.

Yep! Thanks for the report :)
