### ISSUE TITLE
Add scraper for dataengineeringpodcast

### ISSUE THREAD

**Issue by Sangarshanan** [vinayak-mehta/conrad#84]
Scrape conferences from https://www.dataengineeringpodcast.com/conferences/

**Comment by kunaljubce** [comment]
Hi, I am working on this enhancement. However I don't find the cfp links on the mentioned URL. As per the existing application design, do we have to go into each sub-url and get those cfp links? Please clarify,

**Comment by Sangarshanan** [comment]
Yes, they only have conference dates and not the cfp dates, but it seems like most of the conferences on dataengineeringpodcast are anyway coming in from other sources. so this is not a priority, maybe you could take a crack at #5 if possible and if you do please check out https://conference-radar.readthedocs.io/en/latest/dev/adding-crawlers.html#writing-a-crawler for guidelines on writing and scheduling crawlers

**Comment by kunaljubce** [comment]
Ok sure. I have actually done most of the work for #113 and hence raised a PR for your review. Meanwhile, I am starting to work on #5

**Comment by vinayak-mehta** [comment]
Thanks for the PR! I'll review and merge it today :+1:

**Comment by vinayak-mehta** [comment]
Reviewed, looking forward to merging it! :cake:

**Comment by vinayak-mehta** [comment]
Deprioritizing this for now.
