### ISSUE TITLE
Need support for ZSH and add more documentation

### ISSUE THREAD

**Issue by riverarodrigoa** [vinayak-mehta/conrad#89]
Hi all, I found very interesting this tool.
I tried to used but It doesn't work on ZSH.
When using the command: `conrad show`, I obtain the message: `zsh: command not found: conrad`.
Do I have to do some configurations before using it?
I tried to find some documentation, but there isn't one for the configuration so I will be helpful to add some for a first run.

Thanks in advance.

**Comment by vinayak-mehta** [comment]
Can you tell me how you installed it?

**Comment by riverarodrigoa** [comment]
I used pip as is suggested on the repository:
`pip install conference-radar`

My environment is:
Ubuntu 16.04.6 LTS
Python 3.5.2
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)

**Comment by vinayak-mehta** [comment]
Can you also tell me if you're using a virtualenv and also paste the output of `pip install conference-radar`?

**Comment by vinayak-mehta** [comment]
@riverarodrigoa Can you also tell me the output of `which python`?

**Comment by Sangarshanan** [comment]
@riverarodrigoa Could have something to do with your PATH variable or zsh config... check this out
https://stackoverflow.com/questions/18428374/commands-not-found-on-zsh

**Comment by vinayak-mehta** [comment]
@riverarodrigoa Having the executable on your PATH should fix it
